// provinciasEcuador.ts
// Provincias de Ecuador con 10 mecánicas por provincia

export const PROVINCIAS_ECUADOR = [
  'Azuay',
  'Bolívar',
  'Cañar',
  'Carchi',
  'Chimborazo',
  'Cotopaxi',
  'El Oro',
  'Esmeraldas',
  'Galápagos',
  'Guayas',
  'Imbabura',
  'Loja',
  'Los Ríos',
  'Manabí',
  'Morona Santiago',
  'Napo',
  'Orellana',
  'Pastaza',
  'Pichincha',
  'Santa Elena',
  'Santo Domingo de los Tsáchilas',
  'Sucumbíos',
  'Tungurahua',
  'Zamora Chinchipe',
] as const;

export type ProvinciaEcuador = typeof PROVINCIAS_ECUADOR[number];

export interface MecanicaUbicacion {
  id: string;
  nombre: string;
  provincia: ProvinciaEcuador;
  direccion: string;
  latitud: number;
  longitud: number;
}

// 10 mecánicas por cada provincia de Ecuador
export const MECANICAS_POR_PROVINCIA: Record<ProvinciaEcuador, MecanicaUbicacion[]> = {
  'Azuay': [
    { id: 'azuay-1', nombre: 'Mecánica Automotriz Cuenca Centro', provincia: 'Azuay', direccion: 'Av. Huayna Cápac y Av. Loja, Cuenca', latitud: -2.9001, longitud: -79.0059 },
    { id: 'azuay-2', nombre: 'Taller Mecánico El Barranco', provincia: 'Azuay', direccion: 'Calle Larga 4-92, Cuenca', latitud: -2.8973, longitud: -79.0044 },
    { id: 'azuay-3', nombre: 'AutoService Azuay', provincia: 'Azuay', direccion: 'Av. España y Av. Paucarbamba, Cuenca', latitud: -2.8853, longitud: -78.9987 },
    { id: 'azuay-4', nombre: 'Mecánica Tungurahua Express', provincia: 'Azuay', direccion: 'Av. Remigio Crespo 2-50, Cuenca', latitud: -2.9078, longitud: -79.0103 },
    { id: 'azuay-5', nombre: 'Taller Mecánico Río Tomebamba', provincia: 'Azuay', direccion: 'Av. 12 de Abril y Av. Solano, Cuenca', latitud: -2.9035, longitud: -79.0071 },
    { id: 'azuay-6', nombre: 'AutoParts & Service Cuenca', provincia: 'Azuay', direccion: 'Av. Gil Ramírez Dávalos 1-85, Cuenca', latitud: -2.8892, longitud: -79.0003 },
    { id: 'azuay-7', nombre: 'Mecánica Diesel Azuay', provincia: 'Azuay', direccion: 'Panamericana Norte Km 3, Cuenca', latitud: -2.8795, longitud: -78.9952 },
    { id: 'azuay-8', nombre: 'Taller Automotriz Gualaceo', provincia: 'Azuay', direccion: 'Av. 3 de Noviembre, Gualaceo', latitud: -2.8925, longitud: -78.7781 },
    { id: 'azuay-9', nombre: 'Mecánica Integral Paute', provincia: 'Azuay', direccion: 'Calle Principal, Paute', latitud: -2.7794, longitud: -78.7597 },
    { id: 'azuay-10', nombre: 'AutoCenter Cuenca Norte', provincia: 'Azuay', direccion: 'Av. Ordóñez Lasso y Av. de las Américas, Cuenca', latitud: -2.8755, longitud: -78.9915 },
  ],
  'Bolívar': [
    { id: 'bolivar-1', nombre: 'Mecánica Guaranda Centro', provincia: 'Bolívar', direccion: 'Av. General Enríquez 701, Guaranda', latitud: -1.5928, longitud: -79.0006 },
    { id: 'bolivar-2', nombre: 'Taller Automotriz Chimborazo', provincia: 'Bolívar', direccion: 'Calle 7 de Mayo y Sucre, Guaranda', latitud: -1.5935, longitud: -79.0012 },
    { id: 'bolivar-3', nombre: 'AutoService Bolívar', provincia: 'Bolívar', direccion: 'Av. Candido Rada 205, Guaranda', latitud: -1.5917, longitud: -78.9998 },
    { id: 'bolivar-4', nombre: 'Mecánica Express Guaranda', provincia: 'Bolívar', direccion: 'Av. Guayaquil 502, Guaranda', latitud: -1.5942, longitud: -79.0021 },
    { id: 'bolivar-5', nombre: 'Taller San Simón', provincia: 'Bolívar', direccion: 'Barrio San Simón, Guaranda', latitud: -1.5889, longitud: -78.9976 },
    { id: 'bolivar-6', nombre: 'AutoParts Bolívar', provincia: 'Bolívar', direccion: 'Av. 9 de Abril 304, Guaranda', latitud: -1.5955, longitud: -79.0034 },
    { id: 'bolivar-7', nombre: 'Mecánica Diesel Guaranda', provincia: 'Bolívar', direccion: 'Panamericana Sur Km 2, Guaranda', latitud: -1.6012, longitud: -79.0089 },
    { id: 'bolivar-8', nombre: 'Taller Automotriz San Miguel', provincia: 'Bolívar', direccion: 'Barrio San Miguel, San Miguel', latitud: -1.6854, longitud: -79.0562 },
    { id: 'bolivar-9', nombre: 'Mecánica Chillanes', provincia: 'Bolívar', direccion: 'Calle Principal, Chillanes', latitud: -1.9564, longitud: -79.0632 },
    { id: 'bolivar-10', nombre: 'AutoCenter Guaranda Sur', provincia: 'Bolívar', direccion: 'Av. Eliza Mariño, Guaranda', latitud: -1.5978, longitud: -79.0055 },
  ],
  'Cañar': [
    { id: 'canar-1', nombre: 'Mecánica Azogues Centro', provincia: 'Cañar', direccion: 'Av. 24 de Mayo 3-45, Azogues', latitud: -2.7403, longitud: -78.8478 },
    { id: 'canar-2', nombre: 'Taller Automotriz Cañar', provincia: 'Cañar', direccion: 'Calle Bolívar 2-18, Azogues', latitud: -2.7389, longitud: -78.8465 },
    { id: 'canar-3', nombre: 'AutoService Cañar', provincia: 'Cañar', direccion: 'Av. Andrés F. Córdova 120, Azogues', latitud: -2.7421, longitud: -78.8492 },
    { id: 'canar-4', nombre: 'Mecánica Express Azogues', provincia: 'Cañar', direccion: 'Av. Ernesto Che Guevara 4-67, Azogues', latitud: -2.7436, longitud: -78.8507 },
    { id: 'canar-5', nombre: 'Taller San Francisco', provincia: 'Cañar', direccion: 'Calle Luis Cordero 1-89, Azogues', latitud: -2.7375, longitud: -78.8454 },
    { id: 'canar-6', nombre: 'AutoParts Cañar', provincia: 'Cañar', direccion: 'Av. Mons. Leonidas Proaño, La Troncal', latitud: -2.4236, longitud: -79.3397 },
    { id: 'canar-7', nombre: 'Mecánica Cañar Norte', provincia: 'Cañar', direccion: 'Panamericana Norte Km 1, Azogues', latitud: -2.7332, longitud: -78.8421 },
    { id: 'canar-8', nombre: 'Taller Biblián', provincia: 'Cañar', direccion: 'Calle Principal, Biblián', latitud: -2.7175, longitud: -78.8792 },
    { id: 'canar-9', nombre: 'Mecánica La Troncal Sur', provincia: 'Cañar', direccion: 'Av. 25 de Agosto, La Troncal', latitud: -2.4289, longitud: -79.3425 },
    { id: 'canar-10', nombre: 'AutoCenter Azogues', provincia: 'Cañar', direccion: 'Av. Ernesto Che Guevara y Av. 16 de Abril, Azogues', latitud: -2.7454, longitud: -78.8531 },
  ],
  'Carchi': [
    { id: 'carchi-1', nombre: 'Mecánica Tulcán Centro', provincia: 'Carchi', direccion: 'Av. Universitaria y Sucre, Tulcán', latitud: 0.8117, longitud: -77.7178 },
    { id: 'carchi-2', nombre: 'Taller Frontera Norte', provincia: 'Carchi', direccion: 'Av. Veintimilla 52-31, Tulcán', latitud: 0.8134, longitud: -77.7195 },
    { id: 'carchi-3', nombre: 'AutoService Carchi', provincia: 'Carchi', direccion: 'Calle Bolívar 10-45, Tulcán', latitud: 0.8089, longitud: -77.7151 },
    { id: 'carchi-4', nombre: 'Mecánica Express Tulcán', provincia: 'Carchi', direccion: 'Av. Coral y Ayacucho, Tulcán', latitud: 0.8156, longitud: -77.7212 },
    { id: 'carchi-5', nombre: 'Taller El Ángel', provincia: 'Carchi', direccion: 'Calle García Moreno, El Ángel', latitud: 0.6213, longitud: -77.9384 },
    { id: 'carchi-6', nombre: 'AutoParts Carchi', provincia: 'Carchi', direccion: 'Panamericana Norte Km 2, Tulcán', latitud: 0.8201, longitud: -77.7245 },
    { id: 'carchi-7', nombre: 'Mecánica San Gabriel', provincia: 'Carchi', direccion: 'Av. Montúfar, San Gabriel', latitud: 0.5978, longitud: -77.8312 },
    { id: 'carchi-8', nombre: 'Taller Tulcán Sur', provincia: 'Carchi', direccion: 'Av. Rafael Arellano, Tulcán', latitud: 0.8067, longitud: -77.7134 },
    { id: 'carchi-9', nombre: 'Mecánica Mira', provincia: 'Carchi', direccion: 'Calle Principal, Mira', latitud: 0.4534, longitud: -78.1123 },
    { id: 'carchi-10', nombre: 'AutoCenter Tulcán', provincia: 'Carchi', direccion: 'Av. Universitaria y Av. Coral, Tulcán', latitud: 0.8145, longitud: -77.7203 },
  ],
  'Chimborazo': [
    { id: 'chimborazo-1', nombre: 'Mecánica Riobamba Centro', provincia: 'Chimborazo', direccion: 'Av. Daniel León Borja 42-31, Riobamba', latitud: -1.6635, longitud: -78.6548 },
    { id: 'chimborazo-2', nombre: 'Taller Automotriz Chimborazo', provincia: 'Chimborazo', direccion: 'Calle España y Juan Montalvo, Riobamba', latitud: -1.6652, longitud: -78.6562 },
    { id: 'chimborazo-3', nombre: 'AutoService Riobamba', provincia: 'Chimborazo', direccion: 'Av. Canónigo Ramos 24-18, Riobamba', latitud: -1.6687, longitud: -78.6589 },
    { id: 'chimborazo-4', nombre: 'Mecánica Express Chimborazo', provincia: 'Chimborazo', direccion: 'Av. Lizarzaburu y Av. de la Prensa, Riobamba', latitud: -1.6702, longitud: -78.6604 },
    { id: 'chimborazo-5', nombre: 'Taller La Estación', provincia: 'Chimborazo', direccion: 'Av. Unidad Nacional 32-57, Riobamba', latitud: -1.6617, longitud: -78.6532 },
    { id: 'chimborazo-6', nombre: 'AutoParts Chimborazo', provincia: 'Chimborazo', direccion: 'Av. Edelberto Bonilla Oleas, Riobamba', latitud: -1.6578, longitud: -78.6497 },
    { id: 'chimborazo-7', nombre: 'Mecánica Guano', provincia: 'Chimborazo', direccion: 'Av. 20 de Diciembre, Guano', latitud: -1.6078, longitud: -78.6301 },
    { id: 'chimborazo-8', nombre: 'Taller Alausí', provincia: 'Chimborazo', direccion: 'Calle 5 de Junio, Alausí', latitud: -2.2001, longitud: -78.8445 },
    { id: 'chimborazo-9', nombre: 'Mecánica Chambo', provincia: 'Chimborazo', direccion: 'Panamericana Sur, Chambo', latitud: -1.7123, longitud: -78.5954 },
    { id: 'chimborazo-10', nombre: 'AutoCenter Riobamba Norte', provincia: 'Chimborazo', direccion: 'Av. Lizarzaburu y Av. Charles Darwin, Riobamba', latitud: -1.6534, longitud: -78.6456 },
  ],
  'Cotopaxi': [
    { id: 'cotopaxi-1', nombre: 'Mecánica Latacunga Centro', provincia: 'Cotopaxi', direccion: 'Av. Eloy Alfaro 51-64, Latacunga', latitud: -0.9346, longitud: -78.6159 },
    { id: 'cotopaxi-2', nombre: 'Taller Panamericana', provincia: 'Cotopaxi', direccion: 'Av. 5 de Junio y Av. Rumiñahui, Latacunga', latitud: -0.9378, longitud: -78.6187 },
    { id: 'cotopaxi-3', nombre: 'AutoService Cotopaxi', provincia: 'Cotopaxi', direccion: 'Av. Amazonas 10-23, Latacunga', latitud: -0.9312, longitud: -78.6128 },
    { id: 'cotopaxi-4', nombre: 'Mecánica Express Latacunga', provincia: 'Cotopaxi', direccion: 'Calle Quito 72-31, Latacunga', latitud: -0.9394, longitud: -78.6203 },
    { id: 'cotopaxi-5', nombre: 'Taller Salcedo', provincia: 'Cotopaxi', direccion: 'Av. Velasco Ibarra, Salcedo', latitud: -1.0478, longitud: -78.5912 },
    { id: 'cotopaxi-6', nombre: 'AutoParts Cotopaxi', provincia: 'Cotopaxi', direccion: 'Av. Unidad Nacional, Latacunga', latitud: -0.9267, longitud: -78.6091 },
    { id: 'cotopaxi-7', nombre: 'Mecánica Pujilí', provincia: 'Cotopaxi', direccion: 'Calle Principal, Pujilí', latitud: -0.9578, longitud: -78.6934 },
    { id: 'cotopaxi-8', nombre: 'Taller Saquisilí', provincia: 'Cotopaxi', direccion: 'Av. 24 de Mayo, Saquisilí', latitud: -0.8256, longitud: -78.6698 },
    { id: 'cotopaxi-9', nombre: 'Mecánica La Maná', provincia: 'Cotopaxi', direccion: 'Av. 19 de Mayo, La Maná', latitud: -0.9423, longitud: -79.2256 },
    { id: 'cotopaxi-10', nombre: 'AutoCenter Latacunga Norte', provincia: 'Cotopaxi', direccion: 'Av. Eloy Alfaro y Av. Amazonas, Latacunga', latitud: -0.9289, longitud: -78.6112 },
  ],
  'El Oro': [
    { id: 'eloro-1', nombre: 'Mecánica Machala Centro', provincia: 'El Oro', direccion: 'Av. 25 de Junio y Av. Buenavista, Machala', latitud: -3.2582, longitud: -79.9553 },
    { id: 'eloro-2', nombre: 'Taller Puerto Bolívar', provincia: 'El Oro', direccion: 'Calle Principal, Puerto Bolívar', latitud: -3.2689, longitud: -79.9987 },
    { id: 'eloro-3', nombre: 'AutoService El Oro', provincia: 'El Oro', direccion: 'Av. Rocafuerte 12-45, Machala', latitud: -3.2612, longitud: -79.9578 },
    { id: 'eloro-4', nombre: 'Mecánica Express Machala', provincia: 'El Oro', direccion: 'Av. Ferroviaria 8-67, Machala', latitud: -3.2543, longitud: -79.9524 },
    { id: 'eloro-5', nombre: 'Taller Pasaje', provincia: 'El Oro', direccion: 'Av. 8 de Noviembre, Pasaje', latitud: -3.3267, longitud: -79.8067 },
    { id: 'eloro-6', nombre: 'AutoParts Machala', provincia: 'El Oro', direccion: 'Av. Madero Vargas, Machala', latitud: -3.2667, longitud: -79.9634 },
    { id: 'eloro-7', nombre: 'Mecánica Santa Rosa', provincia: 'El Oro', direccion: 'Av. del Ejército, Santa Rosa', latitud: -3.4489, longitud: -79.9589 },
    { id: 'eloro-8', nombre: 'Taller Huaquillas', provincia: 'El Oro', direccion: 'Av. La República, Huaquillas', latitud: -3.4756, longitud: -80.2312 },
    { id: 'eloro-9', nombre: 'Mecánica Arenillas', provincia: 'El Oro', direccion: 'Calle Principal, Arenillas', latitud: -3.5567, longitud: -80.0656 },
    { id: 'eloro-10', nombre: 'AutoCenter Machala Norte', provincia: 'El Oro', direccion: 'Av. 25 de Junio y Av. Circunvalación Norte, Machala', latitud: -3.2498, longitud: -79.9489 },
  ],
  'Esmeraldas': [
    { id: 'esmeraldas-1', nombre: 'Mecánica Esmeraldas Centro', provincia: 'Esmeraldas', direccion: 'Av. Libertad y Bolívar, Esmeraldas', latitud: 0.9681, longitud: -79.6511 },
    { id: 'esmeraldas-2', nombre: 'Taller Las Palmas', provincia: 'Esmeraldas', direccion: 'Av. Kennedy 5-78, Esmeraldas', latitud: 0.9703, longitud: -79.6534 },
    { id: 'esmeraldas-3', nombre: 'AutoService Esmeraldas', provincia: 'Esmeraldas', direccion: 'Calle Olmedo 12-34, Esmeraldas', latitud: 0.9656, longitud: -79.6489 },
    { id: 'esmeraldas-4', nombre: 'Mecánica Express Atacames', provincia: 'Esmeraldas', direccion: 'Av. Principal, Atacames', latitud: 0.8672, longitud: -79.8456 },
    { id: 'esmeraldas-5', nombre: 'Taller Sua', provincia: 'Esmeraldas', direccion: 'Calle Malecón, Sua', latitud: 0.7534, longitud: -80.0378 },
    { id: 'esmeraldas-6', nombre: 'AutoParts Esmeraldas', provincia: 'Esmeraldas', direccion: 'Av. Manuela Cañizares, Esmeraldas', latitud: 0.9734, longitud: -79.6567 },
    { id: 'esmeraldas-7', nombre: 'Mecánica Quinindé', provincia: 'Esmeraldas', direccion: 'Av. 7 de Agosto, Quinindé', latitud: 0.3287, longitud: -79.4712 },
    { id: 'esmeraldas-8', nombre: 'Taller Muisne', provincia: 'Esmeraldas', direccion: 'Av. Malecón, Muisne', latitud: 0.6098, longitud: -80.0234 },
    { id: 'esmeraldas-9', nombre: 'Mecánica San Lorenzo', provincia: 'Esmeraldas', direccion: 'Calle Principal, San Lorenzo', latitud: 1.2856, longitud: -78.8367 },
    { id: 'esmeraldas-10', nombre: 'AutoCenter Esmeraldas Norte', provincia: 'Esmeraldas', direccion: 'Av. Libertad y Av. Kennedy, Esmeraldas', latitud: 0.9712, longitud: -79.6545 },
  ],
  'Galápagos': [
    { id: 'galapagos-1', nombre: 'Mecánica Puerto Ayora', provincia: 'Galápagos', direccion: 'Av. Charles Darwin, Puerto Ayora', latitud: -0.7442, longitud: -90.3117 },
    { id: 'galapagos-2', nombre: 'Taller Isla Santa Cruz', provincia: 'Galápagos', direccion: 'Calle Baltra, Puerto Ayora', latitud: -0.7456, longitud: -90.3134 },
    { id: 'galapagos-3', nombre: 'AutoService Galápagos', provincia: 'Galápagos', direccion: 'Av. Baltra y Av. Charles Binford, Puerto Ayora', latitud: -0.7428, longitud: -90.3101 },
    { id: 'galapagos-4', nombre: 'Mecánica Puerto Baquerizo', provincia: 'Galápagos', direccion: 'Malecón Charles Darwin, Puerto Baquerizo Moreno', latitud: -0.9014, longitud: -89.6102 },
    { id: 'galapagos-5', nombre: 'Taller Isla San Cristóbal', provincia: 'Galápagos', direccion: 'Av. Northe Charles Binford Ave', latitud: -0.9034, longitud: -89.6123 },
    { id: 'galapagos-6', nombre: 'AutoParts Galápagos', provincia: 'Galápagos', direccion: 'Calle Melville, Puerto Ayora', latitud: -0.7471, longitud: -90.3149 },
    { id: 'galapagos-7', nombre: 'Mecánica Puerto Villamil', provincia: 'Galápagos', direccion: 'Av. Antonio Gil, Puerto Villamil', latitud: -0.9567, longitud: -90.9656 },
    { id: 'galapagos-8', nombre: 'Taller Isla Isabela', provincia: 'Galápagos', direccion: 'Calle Las Fragatas, Puerto Villamil', latitud: -0.9589, longitud: -90.9678 },
    { id: 'galapagos-9', nombre: 'Mecánica Academy Bay', provincia: 'Galápagos', direccion: 'Av. Charles Darwin y Av. Baltra, Puerto Ayora', latitud: -0.7413, longitud: -90.3089 },
    { id: 'galapagos-10', nombre: 'AutoCenter Santa Cruz', provincia: 'Galápagos', direccion: 'Calle Tomás de Berlanga, Puerto Ayora', latitud: -0.7485, longitud: -90.3162 },
  ],
  'Guayas': [
    { id: 'guayas-1', nombre: 'Mecánica Guayaquil Norte', provincia: 'Guayas', direccion: 'Av. Francisco de Orellana Mz 111, Guayaquil', latitud: -2.1458, longitud: -79.8868 },
    { id: 'guayas-2', nombre: 'Taller Kennedy Norte', provincia: 'Guayas', direccion: 'Av. Luis Plaza Dañín y Av. del Bombero, Guayaquil', latitud: -2.1534, longitud: -79.8923 },
    { id: 'guayas-3', nombre: 'AutoService Samborondón', provincia: 'Guayas', direccion: 'Av. Samborondón Km 1.5, Samborondón', latitud: -2.1278, longitud: -79.8745 },
    { id: 'guayas-4', nombre: 'Mecánica Express Urdesa', provincia: 'Guayas', direccion: 'Av. Víctor Emilio Estrada 503, Guayaquil', latitud: -2.1689, longitud: -79.9034 },
    { id: 'guayas-5', nombre: 'Taller Alborada', provincia: 'Guayas', direccion: 'Av. Rodolfo Baquerizo Nazur Mz 15, Guayaquil', latitud: -2.1123, longitud: -79.9124 },
    { id: 'guayas-6', nombre: 'AutoParts Guayaquil', provincia: 'Guayas', direccion: 'Av. Juan Tanca Marengo Km 2.5, Guayaquil', latitud: -2.1756, longitud: -79.9156 },
    { id: 'guayas-7', nombre: 'Mecánica Durán', provincia: 'Guayas', direccion: 'Av. 25 de Julio y Eloy Alfaro, Durán', latitud: -2.1734, longitud: -79.8356 },
    { id: 'guayas-8', nombre: 'Taller Daule', provincia: 'Guayas', direccion: 'Av. León Febres Cordero, Daule', latitud: -1.8623, longitud: -79.9789 },
    { id: 'guayas-9', nombre: 'Mecánica Milagro', provincia: 'Guayas', direccion: 'Av. García Moreno 200, Milagro', latitud: -2.1345, longitud: -79.5912 },
    { id: 'guayas-10', nombre: 'AutoCenter Guayaquil Sur', provincia: 'Guayas', direccion: 'Av. 25 de Julio y Av. Domingo Comín, Guayaquil', latitud: -2.2134, longitud: -79.8967 },
  ],
  'Imbabura': [
    { id: 'imbabura-1', nombre: 'Mecánica Ibarra Centro', provincia: 'Imbabura', direccion: 'Av. Atahualpa 4-56, Ibarra', latitud: -0.3499, longitud: -78.1257 },
    { id: 'imbabura-2', nombre: 'Taller Yahuarcocha', provincia: 'Imbabura', direccion: 'Av. Jaime Rivadeneira, Ibarra', latitud: -0.3678, longitud: -78.1345 },
    { id: 'imbabura-3', nombre: 'AutoService Imbabura', provincia: 'Imbabura', direccion: 'Av. Mariano Acosta 18-24, Ibarra', latitud: -0.3467, longitud: -78.1234 },
    { id: 'imbabura-4', nombre: 'Mecánica Express Otavalo', provincia: 'Imbabura', direccion: 'Av. 31 de Octubre y Av. Atahualpa, Otavalo', latitud: 0.2345, longitud: -78.2612 },
    { id: 'imbabura-5', nombre: 'Taller Cotacachi', provincia: 'Imbabura', direccion: 'Av. 10 de Agosto, Cotacachi', latitud: 0.2978, longitud: -78.2634 },
    { id: 'imbabura-6', nombre: 'AutoParts Imbabura', provincia: 'Imbabura', direccion: 'Panamericana Norte Km 3, Ibarra', latitud: -0.3412, longitud: -78.1189 },
    { id: 'imbabura-7', nombre: 'Mecánica Pimampiro', provincia: 'Imbabura', direccion: 'Calle Principal, Pimampiro', latitud: 0.3812, longitud: -77.9567 },
    { id: 'imbabura-8', nombre: 'Taller Atuntaqui', provincia: 'Imbabura', direccion: 'Av. 10 de Agosto, Atuntaqui', latitud: 0.3289, longitud: -78.2145 },
    { id: 'imbabura-9', nombre: 'Mecánica San Antonio', provincia: 'Imbabura', direccion: 'Panamericana Norte, San Antonio', latitud: -0.3234, longitud: -78.1456 },
    { id: 'imbabura-10', nombre: 'AutoCenter Ibarra Norte', provincia: 'Imbabura', direccion: 'Av. Atahualpa y Av. Mariano Acosta, Ibarra', latitud: -0.3445, longitud: -78.1212 },
  ],
  'Loja': [
    { id: 'loja-1', nombre: 'Mecánica Loja Centro', provincia: 'Loja', direccion: 'Av. Universitaria y José Antonio Eguiguren, Loja', latitud: -3.9951, longitud: -79.2032 },
    { id: 'loja-2', nombre: 'Taller La Tebaida', provincia: 'Loja', direccion: 'Av. Salvador Bustamante Celi, Loja', latitud: -3.9978, longitud: -79.2056 },
    { id: 'loja-3', nombre: 'AutoService Loja', provincia: 'Loja', direccion: 'Av. Nueva Loja 14-67, Loja', latitud: -3.9923, longitud: -79.2012 },
    { id: 'loja-4', nombre: 'Mecánica Express Catamayo', provincia: 'Loja', direccion: 'Av. Isidro Ayora, Catamayo', latitud: -3.9867, longitud: -79.3589 },
    { id: 'loja-5', nombre: 'Taller Macará', provincia: 'Loja', direccion: 'Calle Principal, Macará', latitud: -4.3823, longitud: -79.9412 },
    { id: 'loja-6', nombre: 'AutoParts Loja', provincia: 'Loja', direccion: 'Av. 8 de Diciembre, Loja', latitud: -4.0012, longitud: -79.2089 },
    { id: 'loja-7', nombre: 'Mecánica Catacocha', provincia: 'Loja', direccion: 'Av. 18 de Noviembre, Catacocha', latitud: -4.0657, longitud: -79.6456 },
    { id: 'loja-8', nombre: 'Taller Cariamanga', provincia: 'Loja', direccion: 'Av. Loja, Cariamanga', latitud: -4.3289, longitud: -79.5567 },
    { id: 'loja-9', nombre: 'Mecánica Gonzanamá', provincia: 'Loja', direccion: 'Calle Principal, Gonzanamá', latitud: -4.2345, longitud: -79.4378 },
    { id: 'loja-10', nombre: 'AutoCenter Loja Norte', provincia: 'Loja', direccion: 'Av. Universitaria y Av. Salvador Bustamante Celi, Loja', latitud: -3.9934, longitud: -79.2023 },
  ],
  'Los Ríos': [
    { id: 'losrios-1', nombre: 'Mecánica Babahoyo Centro', provincia: 'Los Ríos', direccion: 'Av. 6 de Octubre y Av. 10 de Agosto, Babahoyo', latitud: -1.8023, longitud: -79.5345 },
    { id: 'losrios-2', nombre: 'Taller Quevedo Norte', provincia: 'Los Ríos', direccion: 'Av. 7 de Octubre 612, Quevedo', latitud: -1.0223, longitud: -79.4634 },
    { id: 'losrios-3', nombre: 'AutoService Los Ríos', provincia: 'Los Ríos', direccion: 'Calle Bolívar 203, Babahoyo', latitud: -1.8045, longitud: -79.5367 },
    { id: 'losrios-4', nombre: 'Mecánica Express Quevedo', provincia: 'Los Ríos', direccion: 'Av. June 7 y Av. Walter Andrade, Quevedo', latitud: -1.0256, longitud: -79.4678 },
    { id: 'losrios-5', nombre: 'Taller Ventanas', provincia: 'Los Ríos', direccion: 'Av. Eloy Alfaro, Ventanas', latitud: -1.4523, longitud: -79.4612 },
    { id: 'losrios-6', nombre: 'AutoParts Los Ríos', provincia: 'Los Ríos', direccion: 'Av. General Barona, Babahoyo', latitud: -1.8089, longitud: -79.5389 },
    { id: 'losrios-7', nombre: 'Mecánica Vinces', provincia: 'Los Ríos', direccion: 'Av. 10 de Agosto, Vinces', latitud: -1.5567, longitud: -79.7456 },
    { id: 'losrios-8', nombre: 'Taller Montalvo', provincia: 'Los Ríos', direccion: 'Calle Principal, Montalvo', latitud: -1.7867, longitud: -79.2934 },
    { id: 'losrios-9', nombre: 'Mecánica Puebloviejo', provincia: 'Los Ríos', direccion: 'Av. Principal, Puebloviejo', latitud: -1.5623, longitud: -79.5234 },
    { id: 'losrios-10', nombre: 'AutoCenter Babahoyo', provincia: 'Los Ríos', direccion: 'Av. 6 de Octubre y Av. General Barona, Babahoyo', latitud: -1.8067, longitud: -79.5378 },
  ],
  'Manabí': [
    { id: 'manabi-1', nombre: 'Mecánica Portoviejo Centro', provincia: 'Manabí', direccion: 'Av. Universitaria y Av. Manabí, Portoviejo', latitud: -1.0537, longitud: -80.4551 },
    { id: 'manabi-2', nombre: 'Taller Manta Norte', provincia: 'Manabí', direccion: 'Av. 4 de Noviembre y Av. 24 de Mayo, Manta', latitud: -0.9462, longitud: -80.7249 },
    { id: 'manabi-3', nombre: 'AutoService Manabí', provincia: 'Manabí', direccion: 'Calle 10 de Agosto 502, Portoviejo', latitud: -1.0568, longitud: -80.4578 },
    { id: 'manabi-4', nombre: 'Mecánica Express Manta', provincia: 'Manabí', direccion: 'Av. Malecón 105, Manta', latitud: -0.9493, longitud: -80.7278 },
    { id: 'manabi-5', nombre: 'Taller Chone', provincia: 'Manabí', direccion: 'Av. Eloy Alfaro, Chone', latitud: -0.6938, longitud: -80.0957 },
    { id: 'manabi-6', nombre: 'AutoParts Manabí', provincia: 'Manabí', direccion: 'Av. Reales Tamarindos, Portoviejo', latitud: -1.0489, longitud: -80.4512 },
    { id: 'manabi-7', nombre: 'Mecánica Jipijapa', provincia: 'Manabí', direccion: 'Av. 9 de Octubre, Jipijapa', latitud: -1.3489, longitud: -80.5789 },
    { id: 'manabi-8', nombre: 'Taller Bahía de Caráquez', provincia: 'Manabí', direccion: 'Malecón Alberto Santos, Bahía de Caráquez', latitud: -0.5978, longitud: -80.4234 },
    { id: 'manabi-9', nombre: 'Mecánica Pedernales', provincia: 'Manabí', direccion: 'Av. Principal, Pedernales', latitud: 0.0723, longitud: -80.0534 },
    { id: 'manabi-10', nombre: 'AutoCenter Portoviejo', provincia: 'Manabí', direccion: 'Av. Universitaria y Av. Reales Tamarindos, Portoviejo', latitud: -1.0512, longitud: -80.4534 },
  ],
  'Morona Santiago': [
    { id: 'moronasantiago-1', nombre: 'Mecánica Macas Centro', provincia: 'Morona Santiago', direccion: 'Av. 29 de Mayo y Domingo Comín, Macas', latitud: -2.3089, longitud: -78.1156 },
    { id: 'moronasantiago-2', nombre: 'Taller Sucúa', provincia: 'Morona Santiago', direccion: 'Av. Principal, Sucúa', latitud: -2.4612, longitud: -78.1689 },
    { id: 'moronasantiago-3', nombre: 'AutoService Morona', provincia: 'Morona Santiago', direccion: 'Calle Bolívar 304, Macas', latitud: -2.3112, longitud: -78.1178 },
    { id: 'moronasantiago-4', nombre: 'Mecánica Gualaquiza', provincia: 'Morona Santiago', direccion: 'Av. Gonzalo Pizarro, Gualaquiza', latitud: -3.3978, longitud: -78.5678 },
    { id: 'moronasantiago-5', nombre: 'Taller Méndez', provincia: 'Morona Santiago', direccion: 'Calle Principal, Méndez', latitud: -2.7234, longitud: -78.3012 },
    { id: 'moronasantiago-6', nombre: 'AutoParts Macas', provincia: 'Morona Santiago', direccion: 'Av. 29 de Mayo 512, Macas', latitud: -2.3134, longitud: -78.1189 },
    { id: 'moronasantiago-7', nombre: 'Mecánica Limón Indanza', provincia: 'Morona Santiago', direccion: 'Calle Principal, Limón Indanza', latitud: -2.9723, longitud: -78.4256 },
    { id: 'moronasantiago-8', nombre: 'Taller Palora', provincia: 'Morona Santiago', direccion: 'Av. Principal, Palora', latitud: -1.7012, longitud: -77.9623 },
    { id: 'moronasantiago-9', nombre: 'Mecánica Santiago', provincia: 'Morona Santiago', direccion: 'Av. Río Upano, Santiago', latitud: -2.7689, longitud: -77.8345 },
    { id: 'moronasantiago-10', nombre: 'AutoCenter Macas', provincia: 'Morona Santiago', direccion: 'Av. 29 de Mayo y Av. Domingo Comín, Macas', latitud: -2.3145, longitud: -78.1198 },
  ],
  'Napo': [
    { id: 'napo-1', nombre: 'Mecánica Tena Centro', provincia: 'Napo', direccion: 'Av. 15 de Noviembre y Av. Jumandy, Tena', latitud: -0.9889, longitud: -77.8156 },
    { id: 'napo-2', nombre: 'Taller Archidona', provincia: 'Napo', direccion: 'Av. Principal, Archidona', latitud: -0.9145, longitud: -77.8078 },
    { id: 'napo-3', nombre: 'AutoService Napo', provincia: 'Napo', direccion: 'Calle García Moreno 203, Tena', latitud: -0.9912, longitud: -77.8178 },
    { id: 'napo-4', nombre: 'Mecánica El Chaco', provincia: 'Napo', direccion: 'Av. Principal, El Chaco', latitud: -0.3278, longitud: -77.8156 },
    { id: 'napo-5', nombre: 'Taller Baeza', provincia: 'Napo', direccion: 'Calle Principal, Baeza', latitud: -0.4567, longitud: -77.8889 },
    { id: 'napo-6', nombre: 'AutoParts Napo', provincia: 'Napo', direccion: 'Av. 15 de Noviembre 412, Tena', latitud: -0.9934, longitud: -77.8189 },
    { id: 'napo-7', nombre: 'Mecánica Quijos', provincia: 'Napo', direccion: 'Panamericana Este, Quijos', latitud: -0.2834, longitud: -77.9012 },
    { id: 'napo-8', nombre: 'Taller Cosanga', provincia: 'Napo', direccion: 'Calle Principal, Cosanga', latitud: -0.5812, longitud: -77.8756 },
    { id: 'napo-9', nombre: 'Mecánica Puerto Misahuallí', provincia: 'Napo', direccion: 'Av. Malecón, Puerto Misahuallí', latitud: -1.0356, longitud: -77.6678 },
    { id: 'napo-10', nombre: 'AutoCenter Tena', provincia: 'Napo', direccion: 'Av. 15 de Noviembre y Av. Jumandy, Tena', latitud: -0.9901, longitud: -77.8167 },
  ],
  'Orellana': [
    { id: 'orellana-1', nombre: 'Mecánica Puerto Francisco de Orellana', provincia: 'Orellana', direccion: 'Av. 9 de Octubre y Av. Alejandro Labaka, Coca', latitud: -0.4658, longitud: -76.9869 },
    { id: 'orellana-2', nombre: 'Taller Coca Norte', provincia: 'Orellana', direccion: 'Av. Napo 412, Coca', latitud: -0.4612, longitud: -76.9823 },
    { id: 'orellana-3', nombre: 'AutoService Orellana', provincia: 'Orellana', direccion: 'Calle Quito 205, Coca', latitud: -0.4689, longitud: -76.9902 },
    { id: 'orellana-4', nombre: 'Mecánica La Joya de los Sachas', provincia: 'Orellana', direccion: 'Av. Principal, La Joya de los Sachas', latitud: -0.3567, longitud: -76.8734 },
    { id: 'orellana-5', nombre: 'Taller Loreto', provincia: 'Orellana', direccion: 'Calle Principal, Loreto', latitud: -0.6789, longitud: -77.2856 },
    { id: 'orellana-6', nombre: 'AutoParts Orellana', provincia: 'Orellana', direccion: 'Av. 9 de Octubre 612, Coca', latitud: -0.4734, longitud: -76.9934 },
    { id: 'orellana-7', nombre: 'Mecánica Dayuma', provincia: 'Orellana', direccion: 'Av. Principal, Dayuma', latitud: -0.4089, longitud: -76.9456 },
    { id: 'orellana-8', nombre: 'Taller Nuevo Rocafuerte', provincia: 'Orellana', direccion: 'Malecón del Napo, Nuevo Rocafuerte', latitud: -0.9234, longitud: -75.4089 },
    { id: 'orellana-9', nombre: 'Mecánica Tiputini', provincia: 'Orellana', direccion: 'Vía Auca, Tiputini', latitud: -0.7156, longitud: -75.5234 },
    { id: 'orellana-10', nombre: 'AutoCenter Coca', provincia: 'Orellana', direccion: 'Av. 9 de Octubre y Av. Alejandro Labaka, Coca', latitud: -0.4678, longitud: -76.9889 },
  ],
  'Pastaza': [
    { id: 'pastaza-1', nombre: 'Mecánica Puyo Centro', provincia: 'Pastaza', direccion: 'Av. Alberto Zambrano Palacios y 27 de Febrero, Puyo', latitud: -1.4869, longitud: -78.0009 },
    { id: 'pastaza-2', nombre: 'Taller Shell', provincia: 'Pastaza', direccion: 'Av. Principal, Shell', latitud: -1.4923, longitud: -78.0567 },
    { id: 'pastaza-3', nombre: 'AutoService Pastaza', provincia: 'Pastaza', direccion: 'Calle 9 de Octubre 412, Puyo', latitud: -1.4892, longitud: -78.0034 },
    { id: 'pastaza-4', nombre: 'Mecánica Mera', provincia: 'Pastaza', direccion: 'Av. Principal, Mera', latitud: -1.4634, longitud: -78.0645 },
    { id: 'pastaza-5', nombre: 'Taller Santa Clara', provincia: 'Pastaza', direccion: 'Calle Principal, Santa Clara', latitud: -1.2567, longitud: -77.8756 },
    { id: 'pastaza-6', nombre: 'AutoParts Pastaza', provincia: 'Pastaza', direccion: 'Av. Alberto Zambrano 512, Puyo', latitud: -1.4912, longitud: -78.0056 },
    { id: 'pastaza-7', nombre: 'Mecánica Arajuno', provincia: 'Pastaza', direccion: 'Calle Principal, Arajuno', latitud: -1.3123, longitud: -77.7345 },
    { id: 'pastaza-8', nombre: 'Taller Fátima', provincia: 'Pastaza', direccion: 'Av. Principal, Fátima', latitud: -1.4389, longitud: -78.0234 },
    { id: 'pastaza-9', nombre: 'Mecánica 10 de Agosto', provincia: 'Pastaza', direccion: 'Barrio 10 de Agosto, Puyo', latitud: -1.4834, longitud: -77.9978 },
    { id: 'pastaza-10', nombre: 'AutoCenter Puyo', provincia: 'Pastaza', direccion: 'Av. Alberto Zambrano y Av. 27 de Febrero, Puyo', latitud: -1.4889, longitud: -78.0023 },
  ],
  'Pichincha': [
    { id: 'pichincha-1', nombre: 'Mecanic Company Quito Norte', provincia: 'Pichincha', direccion: 'Av. Río Coca E10-100 y Isla Pinzón, Quito', latitud: -0.1633, longitud: -78.4767 },
    { id: 'pichincha-2', nombre: 'Taller La Carolina', provincia: 'Pichincha', direccion: 'Av. Amazonas N24-155 y Av. Colón, Quito', latitud: -0.1854, longitud: -78.4856 },
    { id: 'pichincha-3', nombre: 'AutoService Cumbayá', provincia: 'Pichincha', direccion: 'Av. Interoceánica Km 12.5, Cumbayá', latitud: -0.2045, longitud: -78.4234 },
    { id: 'pichincha-4', nombre: 'Mecánica Express El Condado', provincia: 'Pichincha', direccion: 'Av. La Prensa N60-123, Quito', latitud: -0.1178, longitud: -78.4978 },
    { id: 'pichincha-5', nombre: 'Taller Tumbaco', provincia: 'Pichincha', direccion: 'Av. Interoceánica Km 17, Tumbaco', latitud: -0.2178, longitud: -78.3967 },
    { id: 'pichincha-6', nombre: 'AutoParts Quito Centro', provincia: 'Pichincha', direccion: 'Av. 10 de Agosto N25-78, Quito', latitud: -0.2012, longitud: -78.4923 },
    { id: 'pichincha-7', nombre: 'Mecánica Quitumbe', provincia: 'Pichincha', direccion: 'Av. Maldonado S24-120, Quito', latitud: -0.2889, longitud: -78.5467 },
    { id: 'pichincha-8', nombre: 'Taller San Antonio de Pichincha', provincia: 'Pichincha', direccion: 'Panamericana Norte Km 20, San Antonio', latitud: 0.0089, longitud: -78.4456 },
    { id: 'pichincha-9', nombre: 'Mecánica Sangolquí', provincia: 'Pichincha', direccion: 'Av. Luis Cordero y Av. General Rumiñahui, Sangolquí', latitud: -0.3123, longitud: -78.4456 },
    { id: 'pichincha-10', nombre: 'AutoCenter Quito Sur', provincia: 'Pichincha', direccion: 'Av. Mariscal Sucre S31-45, Quito', latitud: -0.2734, longitud: -78.5389 },
  ],
  'Santa Elena': [
    { id: 'santaelena-1', nombre: 'Mecánica Santa Elena Centro', provincia: 'Santa Elena', direccion: 'Av. Gral. Enríquez Gallo, Santa Elena', latitud: -2.2267, longitud: -80.8589 },
    { id: 'santaelena-2', nombre: 'Taller Salinas', provincia: 'Santa Elena', direccion: 'Malecón Salinas 4-56, Salinas', latitud: -2.2145, longitud: -80.9534 },
    { id: 'santaelena-3', nombre: 'AutoService La Libertad', provincia: 'Santa Elena', direccion: 'Av. 9 de Octubre 612, La Libertad', latitud: -2.2378, longitud: -80.9067 },
    { id: 'santaelena-4', nombre: 'Mecánica Ballenita', provincia: 'Santa Elena', direccion: 'Calle Principal, Ballenita', latitud: -2.3234, longitud: -80.6789 },
    { id: 'santaelena-5', nombre: 'Taller Anconcito', provincia: 'Santa Elena', direccion: 'Av. Principal, Anconcito', latitud: -2.3467, longitud: -80.8856 },
    { id: 'santaelena-6', nombre: 'AutoParts Santa Elena', provincia: 'Santa Elena', direccion: 'Av. Principal 304, Santa Elena', latitud: -2.2312, longitud: -80.8623 },
    { id: 'santaelena-7', nombre: 'Mecánica Montañita', provincia: 'Santa Elena', direccion: 'Calle Principal, Montañita', latitud: -1.8278, longitud: -80.7456 },
    { id: 'santaelena-8', nombre: 'Taller Manglaralto', provincia: 'Santa Elena', direccion: 'Av. Principal, Manglaralto', latitud: -1.8834, longitud: -80.7289 },
    { id: 'santaelena-9', nombre: 'Mecánica Ayangue', provincia: 'Santa Elena', direccion: 'Malecón Ayangue, Ayangue', latitud: -1.9123, longitud: -80.7712 },
    { id: 'santaelena-10', nombre: 'AutoCenter La Libertad', provincia: 'Santa Elena', direccion: 'Av. 9 de Octubre y Av. Gral. Enríquez, La Libertad', latitud: -2.2401, longitud: -80.9089 },
  ],
  'Santo Domingo de los Tsáchilas': [
    { id: 'santodomingo-1', nombre: 'Mecánica Santo Domingo Centro', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. Quito 1205, Santo Domingo', latitud: -0.2501, longitud: -79.1751 },
    { id: 'santodomingo-2', nombre: 'Taller Chone', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. Chone Km 2, Santo Domingo', latitud: -0.2434, longitud: -79.1689 },
    { id: 'santodomingo-3', nombre: 'AutoService Tsáchilas', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. 29 de Mayo 512, Santo Domingo', latitud: -0.2534, longitud: -79.1778 },
    { id: 'santodomingo-4', nombre: 'Mecánica Express Santo Domingo', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. de los Tsáchilas 304, Santo Domingo', latitud: -0.2467, longitud: -79.1723 },
    { id: 'santodomingo-5', nombre: 'Taller Bombolí', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Barrio Bombolí, Santo Domingo', latitud: -0.2612, longitud: -79.1834 },
    { id: 'santodomingo-6', nombre: 'AutoParts Santo Domingo', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. Quito 1512, Santo Domingo', latitud: -0.2489, longitud: -79.1745 },
    { id: 'santodomingo-7', nombre: 'Mecánica Zaracay', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. Abraham Calazacón, Santo Domingo', latitud: -0.2578, longitud: -79.1812 },
    { id: 'santodomingo-8', nombre: 'Taller Luz de América', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Barrio Luz de América, Santo Domingo', latitud: -0.2645, longitud: -79.1867 },
    { id: 'santodomingo-9', nombre: 'Mecánica Cooperativa', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Barrio Cooperativa, Santo Domingo', latitud: -0.2389, longitud: -79.1667 },
    { id: 'santodomingo-10', nombre: 'AutoCenter Santo Domingo Norte', provincia: 'Santo Domingo de los Tsáchilas', direccion: 'Av. Quito y Av. 29 de Mayo, Santo Domingo', latitud: -0.2456, longitud: -79.1712 },
  ],
  'Sucumbíos': [
    { id: 'sucumbios-1', nombre: 'Mecánica Nueva Loja Centro', provincia: 'Sucumbíos', direccion: 'Av. Quito 1204, Nueva Loja', latitud: 0.0889, longitud: -76.8878 },
    { id: 'sucumbios-2', nombre: 'Taller Lago Agrio', provincia: 'Sucumbíos', direccion: 'Av. Colombia 512, Nueva Loja', latitud: 0.0856, longitud: -76.8834 },
    { id: 'sucumbios-3', nombre: 'AutoService Sucumbíos', provincia: 'Sucumbíos', direccion: 'Calle 12 de Febrero 304, Nueva Loja', latitud: 0.0912, longitud: -76.8912 },
    { id: 'sucumbios-4', nombre: 'Mecánica Shushufindi', provincia: 'Sucumbíos', direccion: 'Av. Principal, Shushufindi', latitud: -0.1823, longitud: -76.6456 },
    { id: 'sucumbios-5', nombre: 'Taller Cascales', provincia: 'Sucumbíos', direccion: 'Calle Principal, Cascales', latitud: 0.1867, longitud: -77.1345 },
    { id: 'sucumbios-6', nombre: 'AutoParts Sucumbíos', provincia: 'Sucumbíos', direccion: 'Av. Quito 1512, Nueva Loja', latitud: 0.0934, longitud: -76.8945 },
    { id: 'sucumbios-7', nombre: 'Mecánica Cuyabeno', provincia: 'Sucumbíos', direccion: 'Av. Principal, Cuyabeno', latitud: 0.2134, longitud: -76.1789 },
    { id: 'sucumbios-8', nombre: 'Taller Putumayo', provincia: 'Sucumbíos', direccion: 'Calle Principal, Putumayo', latitud: 0.0456, longitud: -75.9234 },
    { id: 'sucumbios-9', nombre: 'Mecánica Gonzalo Pizarro', provincia: 'Sucumbíos', direccion: 'Av. Principal, Gonzalo Pizarro', latitud: 0.5678, longitud: -77.5234 },
    { id: 'sucumbios-10', nombre: 'AutoCenter Nueva Loja', provincia: 'Sucumbíos', direccion: 'Av. Quito y Av. Colombia, Nueva Loja', latitud: 0.0889, longitud: -76.8889 },
  ],
  'Tungurahua': [
    { id: 'tungurahua-1', nombre: 'Mecánica Ambato Centro', provincia: 'Tungurahua', direccion: 'Av. Cevallos 10-45, Ambato', latitud: -1.2490, longitud: -78.6167 },
    { id: 'tungurahua-2', nombre: 'Taller Ficoa', provincia: 'Tungurahua', direccion: 'Av. Los Guaytambos 3-78, Ambato', latitud: -1.2456, longitud: -78.6123 },
    { id: 'tungurahua-3', nombre: 'AutoService Tungurahua', provincia: 'Tungurahua', direccion: 'Av. Rodrigo Pachano 512, Ambato', latitud: -1.2523, longitud: -78.6201 },
    { id: 'tungurahua-4', nombre: 'Mecánica Express Ambato', provincia: 'Tungurahua', direccion: 'Av. Atahualpa 14-67, Ambato', latitud: -1.2567, longitud: -78.6234 },
    { id: 'tungurahua-5', nombre: 'Taller Baños', provincia: 'Tungurahua', direccion: 'Av. Amazonas 204, Baños', latitud: -1.3967, longitud: -78.4234 },
    { id: 'tungurahua-6', nombre: 'AutoParts Tungurahua', provincia: 'Tungurahua', direccion: 'Av. Indoamérica Km 2, Ambato', latitud: -1.2389, longitud: -78.6078 },
    { id: 'tungurahua-7', nombre: 'Mecánica Pelileo', provincia: 'Tungurahua', direccion: 'Av. Confraternidad, Pelileo', latitud: -1.3289, longitud: -78.5456 },
    { id: 'tungurahua-8', nombre: 'Taller Píllaro', provincia: 'Tungurahua', direccion: 'Av. Principal, Píllaro', latitud: -1.1734, longitud: -78.5389 },
    { id: 'tungurahua-9', nombre: 'Mecánica Patate', provincia: 'Tungurahua', direccion: 'Calle Principal, Patate', latitud: -1.3123, longitud: -78.4967 },
    { id: 'tungurahua-10', nombre: 'AutoCenter Ambato Norte', provincia: 'Tungurahua', direccion: 'Av. Cevallos y Av. Atahualpa, Ambato', latitud: -1.2467, longitud: -78.6145 },
  ],
  'Zamora Chinchipe': [
    { id: 'zamorachinchipe-1', nombre: 'Mecánica Zamora Centro', provincia: 'Zamora Chinchipe', direccion: 'Av. Héroes del Cenepa y Av. del Maestro, Zamora', latitud: -4.0667, longitud: -78.9556 },
    { id: 'zamorachinchipe-2', nombre: 'Taller Yantzaza', provincia: 'Zamora Chinchipe', direccion: 'Av. Principal, Yantzaza', latitud: -3.8356, longitud: -78.7567 },
    { id: 'zamorachinchipe-3', nombre: 'AutoService Zamora', provincia: 'Zamora Chinchipe', direccion: 'Calle 24 de Mayo 304, Zamora', latitud: -4.0689, longitud: -78.9578 },
    { id: 'zamorachinchipe-4', nombre: 'Mecánica Zumbi', provincia: 'Zamora Chinchipe', direccion: 'Av. Principal, Zumbi', latitud: -4.0934, longitud: -78.6234 },
    { id: 'zamorachinchipe-5', nombre: 'Taller Chinchipe', provincia: 'Zamora Chinchipe', direccion: 'Calle Principal, Chinchipe', latitud: -4.4234, longitud: -78.9867 },
    { id: 'zamorachinchipe-6', nombre: 'AutoParts Zamora', provincia: 'Zamora Chinchipe', direccion: 'Av. del Maestro 512, Zamora', latitud: -4.0723, longitud: -78.9601 },
    { id: 'zamorachinchipe-7', nombre: 'Mecánica El Pangui', provincia: 'Zamora Chinchipe', direccion: 'Av. Principal, El Pangui', latitud: -3.6123, longitud: -78.5789 },
    { id: 'zamorachinchipe-8', nombre: 'Taller Palanda', provincia: 'Zamora Chinchipe', direccion: 'Calle Principal, Palanda', latitud: -4.6834, longitud: -79.1356 },
    { id: 'zamorachinchipe-9', nombre: 'Mecánica Centinela del Cóndor', provincia: 'Zamora Chinchipe', direccion: 'Av. Principal, Centinela del Cóndor', latitud: -3.5967, longitud: -78.3234 },
    { id: 'zamorachinchipe-10', nombre: 'AutoCenter Zamora', provincia: 'Zamora Chinchipe', direccion: 'Av. Héroes del Cenepa y Av. del Maestro, Zamora', latitud: -4.0689, longitud: -78.9567 },
  ],
};

// Función helper para obtener mecánicas por provincia
export const obtenerMecanicasPorProvincia = (provincia: ProvinciaEcuador): MecanicaUbicacion[] => {
  return MECANICAS_POR_PROVINCIA[provincia] || [];
};

// Función helper para obtener todas las mecánicas
export const obtenerTodasLasMecanicas = (): MecanicaUbicacion[] => {
  return Object.values(MECANICAS_POR_PROVINCIA).flat();
};

// Función helper para obtener una mecánica por ID
export const obtenerMecanicaPorId = (id: string): MecanicaUbicacion | undefined => {
  return obtenerTodasLasMecanicas().find(m => m.id === id);
};
